##############################################
# --- DynamoDB: document-summaries --- #
##############################################

# Keyed by document_id (UUID generated by the processor Lambda).
# On-demand capacity — document uploads are unpredictable in volume.
resource "aws_dynamodb_table" "summaries" {
  name         = "document-summaries"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "document_id"

  attribute {
    name = "document_id"
    type = "S"
  }
}
